// <auto-generated/>
// Sts1ReplacementPrototype.cs - Debug-only RitsuLib patch for event pool replacement.
//
// PURPOSE: When Sts1EventRegistrationMode.ReplaceUnknownEventsPrototype is active,
// this patch intercepts ActModel.GenerateRooms() and replaces the native StS2 event
// pool with only StS1 events. This proves that unknown rooms will not draw native
// StS2 events when the prototype mode is enabled.
//
// SAFETY: This file is compiled by default, but all patch code is gated behind
// REPLACEMENT_PROTOTYPE_ENABLED. It will NOT affect release builds unless that
// debug symbol is deliberately defined.
//
// RUNTIME VERIFICATION: Requires game launch with SPIREPLUS_STS1_EVENT_MODE=ReplaceUnknownEventsPrototype.
// Log evidence should show only StS1 events appearing in unknown rooms.
//
// STATUS: Source-gated prototype only. Runtime replacement behavior remains unverified.

#if REPLACEMENT_PROTOTYPE_ENABLED
using System.Collections.Generic;
using System.Linq;
using HarmonyLib;
using MegaCrit.Sts2.Core.Models;
using MegaCrit.Sts2.Core.Models.Acts;
using MegaCrit.Sts2.Core.Random;
using MegaCrit.Sts2.Core.Unlocks;
using STS2RitsuLib.Patching.Models;

namespace EZMicroBalance.EZMicroBalanceCode.Sts1Events.Runtime;

/// <summary>
/// Debug-only prototype: replaces the native StS2 event pool with StS1 events.
/// Only active when SPIREPLUS_STS1_EVENT_MODE=ReplaceUnknownEventsPrototype.
///
/// This patch proves the concept that unknown rooms can be forced to draw only
/// from the StS1 event pool, preventing native StS2 events from appearing.
///
/// Implementation notes:
/// - Patches ActModel.GenerateRooms() through RitsuLib with a postfix.
/// - After native pool generation, accesses RoomSet.events via reflection
///   (same pattern as UrdaBlessingService.RootSightEvents).
/// - Filters the event list to keep only StS1 event types (namespace check).
/// - If no StS1 events remain (e.g. all exhausted), logs a warning and
///   allows repetition of StS1 events rather than falling back to StS2.
/// </summary>
internal sealed class Sts1ReplacementPrototype : IPatchMethod
{
    static string IPatchMethod.PatchId => "sts1-replacement-prototype-generate-rooms";
    static bool IPatchMethod.IsCritical => false;
    static string IPatchMethod.Description => "Debug-only StS1 unknown-room event-pool replacement prototype";
    static ModPatchTarget[] IPatchMethod.GetTargets() =>
    [
        new ModPatchTarget(
            typeof(ActModel),
            nameof(ActModel.GenerateRooms),
            [typeof(Rng), typeof(UnlockState), typeof(bool)])
    ];

    private static bool IsActive =>
        Sts1EventFeatureGate.ResolveMode() == Sts1EventRegistrationMode.ReplaceUnknownEventsPrototype;

    /// <summary>
    /// Postfix: after native event pool is generated, replace with StS1-only pool.
    /// </summary>
    [HarmonyPostfix]
    private static void Postfix(ActModel __instance)
    {
        if (!IsActive)
            return;

        // Access RoomSet.events via reflection (same pattern as UrdaBlessingService)
        var roomsField = AccessTools.Field(typeof(ActModel), "_rooms");
        if (roomsField?.GetValue(__instance) is not RoomSet rooms)
            return;

        var nativeEvents = rooms.events;
        if (nativeEvents is null || nativeEvents.Count == 0)
            return;

        // Filter to keep only StS1 events (namespace contains "Sts1Events.Models")
        var sts1Events = nativeEvents
            .Where(e => e.GetType().Namespace?.Contains("Sts1Events.Models") == true)
            .ToList();

        if (sts1Events.Count == 0)
        {
            MainFile.Logger.Warn("[StS1 ReplacementPrototype] No StS1 events found in pool; " +
                                 "native StS2 events will remain. Ensure events are registered.");
            return;
        }

        // Replace the native pool with StS1-only events
        nativeEvents.Clear();
        nativeEvents.AddRange(sts1Events);

        MainFile.Logger.Info($"[StS1 ReplacementPrototype] Replaced event pool: " +
                             $"{sts1Events.Count} StS1 events, 0 native StS2 events.");

        // Reset visit counter so StS1 events can be visited from the start
        var visitedField = AccessTools.Field(typeof(RoomSet), "eventsVisited");
        visitedField?.SetValue(rooms, 0);
    }
}
#endif
