<Project Sdk="Godot.NET.Sdk/4.5.1" InitialTargets="CheckDependencyPaths">
    <Import Project=".\Sts2PathDiscovery.props"/>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DefaultItemExcludes>packages/**</DefaultItemExcludes>
        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
        <GodotDisabledSourceGenerators>GodotPluginsInitializer</GodotDisabledSourceGenerators>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);MSB3270;STS001;STS003;STS004</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="EZMicroBalance.Tests" />
    </ItemGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')" >
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>true</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>true</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup Condition="False">
        <Publicize Include="sts2" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="STS2.RitsuLib" Version="0.4.33" PrivateAssets="All"/>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="All"/>
        <PackageReference Include="Alchyr.Sts2.ModAnalyzers" Version="0.1.9" />
        <AdditionalFiles Include="EZMicroBalance/localization/**/*.json"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="EZMicroBalanceCode/**/*.cs" />
        <Compile Remove="EZMicroBalanceCode/Sts1Events/Models/Shared/Sts1Duplicator.cs" />
    </ItemGroup>

    <ItemGroup>
        <None Condition="Exists('Directory.Build.props')" Include="Directory.Build.props"/>
        <None Include=".gitignore" />
        <None Include="EZMicroBalance.json" />
        <None Include="project.godot"/>
        <None Include="EZMicroBalance/**" />
    </ItemGroup>

    <Target Name="CheckDependencyPaths" >
        <Error
                Text=" Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
                Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')" />
    </Target>

    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Release'">
        <Message Text="Copying Spire Plus compatibility DLL and manifest to mods folder." Importance="high" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
        <Copy SourceFiles="$(AssemblyName).json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" />
    </Target>

    <Target Name="NeedGodotForPublish" BeforeTargets="Publish">
        <Error Text=" Godot path must be set up before publishing; Godot not found at path '$(GodotPath)'. Check Directory.Build.props file."
               Condition="'$(GodotPath)' == '' or !Exists('$(GodotPath)')"/>
    </Target>

    <ItemGroup>
        <GodotExportRuntimeReference Include="$(Sts2DataDir)/sts2.dll" Condition="Exists('$(Sts2DataDir)/sts2.dll')" />
        <GodotExportRuntimeReference Include="$(Sts2DataDir)/0Harmony.dll" Condition="Exists('$(Sts2DataDir)/0Harmony.dll')" />
    </ItemGroup>

    <Target Name="CopyGodotExportRuntimeReferences" BeforeTargets="GodotPublish" Condition="'$(IsInnerGodotExport)' != 'true'">
        <Copy SourceFiles="@(GodotExportRuntimeReference)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
        <Copy SourceFiles="@(GodotExportRuntimeReference)" DestinationFolder="$(MSBuildProjectDirectory)\.godot\mono\temp\bin\Debug\" SkipUnchangedFiles="true" />
        <Copy SourceFiles="@(GodotExportRuntimeReference)" DestinationFolder="$(MSBuildProjectDirectory)\.godot\mono\temp\bin\Release\" SkipUnchangedFiles="true" />
    </Target>

    <ItemGroup>
        <GodotPublishInputs Include="EZMicroBalance/**"/>
        <GodotPublishInputs Include="EZMicroBalance.json"/>
        <GodotPublishInputs Include="export_presets.cfg"/>
        <GodotPublishInputs Include="project.godot"/>
    </ItemGroup>

    <Target Name="GodotPublish" AfterTargets="Publish" Condition="'$(GodotPath)' != '' and Exists('$(GodotPath)') and '$(IsInnerGodotExport)' != 'true'" Inputs="@(GodotPublishInputs)" Outputs="$(ModsPath)$(MSBuildProjectName)/$(MSBuildProjectName).pck">
        <Message Text="Exporting Spire Plus compatibility Godot .pck to mods folder" Importance="high"/>
        <Exec Command="&quot;$(GodotPath)&quot; --headless --export-pack &quot;BasicExport&quot; &quot;$(ModsPath)$(MSBuildProjectName)/$(MSBuildProjectName).pck&quot;"
              EnvironmentVariables="IsInnerGodotExport=true;MSBUILDDISABLENODEREUSE=1"/>
    </Target>
</Project>
