param(
    [Parameter(Mandatory = $true)]
    [string]$RepoRoot,

    [Parameter(Mandatory = $true)]
    [string]$GodotPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

function Resolve-FullPath([string]$Path) {
    return [System.IO.Path]::GetFullPath($Path)
}

function Write-Utf8NoBom([string]$Path, [string]$Text) {
    $utf8NoBom = New-Object System.Text.UTF8Encoding -ArgumentList $false
    [System.IO.File]::WriteAllText($Path, $Text, $utf8NoBom)
}

$repoFull = Resolve-FullPath $RepoRoot
$godotFull = Resolve-FullPath $GodotPath
$outputFull = Resolve-FullPath $OutputPath
$tempRoot = Resolve-FullPath (Join-Path $repoFull '.godot\futurepeek-export-root')
$allowedTempRoot = Resolve-FullPath (Join-Path $repoFull '.godot')

if (-not (Test-Path -LiteralPath $godotFull -PathType Leaf)) {
    throw "Godot executable not found: $godotFull"
}

if (-not $tempRoot.StartsWith($allowedTempRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to prepare Future Peek export outside .godot: $tempRoot"
}

if (Test-Path -LiteralPath $tempRoot) {
    Remove-Item -LiteralPath $tempRoot -Recurse -Force
}

New-Item -ItemType Directory -Force -Path (Join-Path $tempRoot 'EZFuturePeek\localization\eng') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $tempRoot 'EZFuturePeek\localization\zhs') | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outputFull) | Out-Null

Copy-Item -LiteralPath (Join-Path $repoFull 'EZFuturePeek\mod_icon.svg') -Destination (Join-Path $tempRoot 'EZFuturePeek\mod_icon.svg') -Force
Copy-Item -LiteralPath (Join-Path $repoFull 'EZFuturePeek\localization\eng\settings_ui.json') -Destination (Join-Path $tempRoot 'EZFuturePeek\localization\eng\settings_ui.json') -Force
Copy-Item -LiteralPath (Join-Path $repoFull 'EZFuturePeek\localization\zhs\settings_ui.json') -Destination (Join-Path $tempRoot 'EZFuturePeek\localization\zhs\settings_ui.json') -Force

$projectFile = @'
; Engine configuration file.
; This temporary project is generated by scripts/export-future-peek.ps1.

[application]

config/name="EZFuturePeek"
config/features=PackedStringArray("4.5", "C#", "Forward Plus")
config/icon="res://EZFuturePeek/mod_icon.svg"

[dotnet]

project/assembly_name="EZFuturePeek"
'@
Write-Utf8NoBom (Join-Path $tempRoot 'project.godot') $projectFile

$exportPresetFile = @'
[preset.0]

name="FuturePeekExport"
platform="Windows Desktop"
runnable=false
advanced_options=false
dedicated_server=false
custom_features=""
export_filter="resources"
export_files=PackedStringArray("res://EZFuturePeek/mod_icon.svg", "res://EZFuturePeek/localization/eng/settings_ui.json", "res://EZFuturePeek/localization/zhs/settings_ui.json")
include_filter="EZFuturePeek/localization/*/*.json"
exclude_filter="*.cs,*.cs.uid,EzDailyContent/*,EzDailyContentCode/*,EZMicroBalance/*,EZMicroBalanceCode/*,art_pipeline/*,asset/*,source code/*,docs/*,legacy/*"
export_path=""
patches=PackedStringArray()
encryption_include_filters=""
encryption_exclude_filters=""
seed=0
encrypt_pck=false
encrypt_directory=false
script_export_mode=2

[preset.0.options]

custom_template/debug=""
custom_template/release=""
debug/export_console_wrapper=1
binary_format/embed_pck=false
texture_format/s3tc_bptc=true
texture_format/etc2_astc=false
shader_baker/enabled=false
binary_format/architecture="msil"
codesign/enable=false
codesign/timestamp=true
codesign/timestamp_server_url=""
codesign/digest_algorithm=1
codesign/description=""
codesign/custom_options=PackedStringArray()
application/modify_resources=false
application/icon="res://EZFuturePeek/mod_icon.svg"
application/console_wrapper_icon="res://EZFuturePeek/mod_icon.svg"
application/icon_interpolation=4
application/file_version=""
application/product_version=""
application/company_name=""
application/product_name=""
application/file_description=""
application/copyright=""
application/trademarks=""
application/export_angle=0
application/export_d3d12=0
application/d3d12_agility_sdk_multiarch=true
ssh_remote_deploy/enabled=false
ssh_remote_deploy/host=""
ssh_remote_deploy/port="22"
ssh_remote_deploy/extra_args_ssh=""
ssh_remote_deploy/extra_args_scp=""
ssh_remote_deploy/run_script=""
ssh_remote_deploy/cleanup_script=""
dotnet/include_scripts_content=false
dotnet/include_debug_symbols=true
dotnet/embed_build_outputs=false
'@
Write-Utf8NoBom (Join-Path $tempRoot 'export_presets.cfg') $exportPresetFile

& $godotFull --headless --path $tempRoot --export-pack FuturePeekExport $outputFull
$godotExitCode = $LASTEXITCODE
if ($null -eq $godotExitCode) {
    $godotExitCode = 0
}

if ($godotExitCode -ne 0) {
    throw "Godot Future Peek export failed with exit code $godotExitCode"
}

if (-not (Test-Path -LiteralPath $outputFull -PathType Leaf)) {
    throw "Godot Future Peek export did not create output PCK: $outputFull"
}
