using Xunit;

namespace EZMicroBalance.Tests;

public sealed class ActiveSourceManifestGuardTests
{
    private static readonly string[] ExpectedActiveSourceFiles =
    [
        "EZMicroBalanceCode/Ancients/Common/AncientCardHelpers.cs",
        "EZMicroBalanceCode/Ancients/Common/AncientFeatureGate.cs",
        "EZMicroBalanceCode/Ancients/Common/AncientPlayerState.cs",
        "EZMicroBalanceCode/Ancients/Common/AncientRewardRelicService.cs",
        "EZMicroBalanceCode/Ancients/Common/AncientInitialOptionReroll.cs",
        "EZMicroBalanceCode/Ancients/Common/AncientSavedStateFields.cs",
        "EZMicroBalanceCode/Ancients/Common/AncientSelectionEvidenceLog.cs",
        "EZMicroBalanceCode/Ancients/Common/JeweledMaskFreePower.cs",
        "EZMicroBalanceCode/Ancients/Patches/ChoicesParadoxPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/ClawsPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/CrossbowPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/JeweledMaskPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/JewelryBoxPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/MeatCleaverCookPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PaelsHornPhase1Patch.cs",
        "EZMicroBalanceCode/Ancients/Patches/PreservedFogPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/DebtAndCardPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/DistinguishedCapePatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/FiddlePatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PaelsToothPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PaelsToothStoredCardService.cs",
        "EZMicroBalanceCode/Ancients/Patches/BlackStarCompensationPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PickupRewardPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PickupRewardService.cs",
        "EZMicroBalanceCode/Ancients/Patches/PickupRewardGatePatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemHoverPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemNormalRewardDecision.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemReplacementCleanup.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemReplacementPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemReplacementPool.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemRewardContextPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemRewardState.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemRewardScreenHintBanner.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemRewardScreenHintBanner.Field.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemRewardScreenHintBanner.Node.cs",
        "EZMicroBalanceCode/Ancients/Patches/PrismaticGemRewardScreenHintPatch.cs",
        "EZMicroBalanceCode/Ancients/Patches/SealOfGoldPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/SovereignBladeForgePatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/ToastyMittensPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/VakuRewardPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/VelvetChokerPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/VelvetChokerSoftLimitTracker.cs",
        "EZMicroBalanceCode/Ancients/Patches/WhisperingEarringPatches.cs",
        "EZMicroBalanceCode/Ancients/Patches/BrightestFlameExhaustDrawPatch.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaAct3AncientService.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaAncient.OptionRows.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaAncient.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaAncient.Options.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaAssetPaths.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingIds.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.CardRules.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.CombatEnd.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.CombatStart.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.CombatState.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.CombatStateReset.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.CostRules.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.ClosedCourt.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.DeathReprieve.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.DeferredVerdict.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.MirrorHallEcho.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.MirrorRebuttal.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.PlayerTurnStart.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.PowerReplacement.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.Presumption.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.PublicEvidence.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.SingleSentence.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.State.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaBlessingService.TurnEnd.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaFeatureGate.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaHooks.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaInitializer.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaOptionRelics.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaPowers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Lotha/LothaRewardSelectionService.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightAssetPaths.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightEncounter.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightFeatureGate.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightOptionRelic.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightPatch.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightPowers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightRunHook.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightService.CombatState.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightService.Entry.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightService.NoRewardResume.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightService.ParentRestore.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightVictoryChoices.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuFightVictory.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuTemptationCard.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Vakuu/VakuuTrialMonster.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviAct2AncientService.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviAncient.OptionRows.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviAncient.Options.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviAncient.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviAssetPaths.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.CardPlayFlow.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.BlueprintProof.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.DebtSettlement.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.ForbiddenLoan.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.Helpers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.MisprintPress.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.OpenBook.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.OverdueLibrary.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.Payments.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.Paperstorm.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.RedInkOverdraft.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.State.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingService.TemporaryCards.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviBlessingIds.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviArchivePageCards.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviFeatureGate.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviHooks.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviInitializer.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviCombatTokenCards.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviOptionRelics.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviPowers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Morvi/MorviRunHook.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaAct1AncientService.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaAncient.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaAncient.OptionRows.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaAncient.Options.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaAssetPaths.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingIds.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaCards.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaFeatureGate.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaInitializer.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.AfterRain.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.CardRewards.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.HumusPact.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.Localization.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.MapHelpers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.MossMap.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.Molting.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaMapUiPatches.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaOptionRelics.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSight.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightEncounters.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightEntryCommit.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightEntryLookup.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightEvents.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightHover.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightMarkers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightPreviewGeneration.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightPreviewStore.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightReservations.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightReservationQueues.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightReservedIds.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightRouting.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightStatus.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightTargets.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightUnknown.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RootSightUnknownOdds.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RouteMapHelpers.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RouteRewards.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.RunLifecycle.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.SeedBank.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.SeedBankExtraction.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.SeedBankStatus.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.Seedbed.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.SeedbedCombat.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.ShallowRootRelic.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.State.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.StateParsing.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.StateSchema.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.TrialBranch.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.TrialBranchDisplay.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaBlessingService.TrialBranchOffer.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRootSightRoomPatches.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRootSightMapClickPatches.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRootSightMapQuestMarker.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRootSightMapPreviewVisuals.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRootedRouteMapQuestMarker.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRewardSelectionService.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaRunHook.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaTrialBranchEnchantment.cs",
        "EZMicroBalanceCode/Ancients/Expansion/Urda/UrdaWitheredHuskTransformPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionA20Patches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionA20RewardScreenPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionMapGenerationPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AeonglassIntentPatches.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionAssetPaths.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.ActiveModifiers.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.ActValues.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Banners.PressingLine.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Banners.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.AeonglassHourglass.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.BoilingCritical.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.ChosenDecree.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.CombatStart.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.Events.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.HolyDaze.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.InkReturn.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.MarginalNote.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.MartyrOath.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.MisalignedShell.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.PhaseCarryover.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.SoulTide.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.StartledShell.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.StruggleBait.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.TurnFlow.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.BossSeals.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Banners.BloodPrize.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Banners.LastStand.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Banners.Shieldwall.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Banners.Vanguard.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Commands.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.CombatEvents.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.CombatLifecycle.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Enemies.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Firemarks.ConstantHeal.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Firemarks.ForgeArmor.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Firemarks.Giant.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Firemarks.Might.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatModifierService.Firemarks.cs",
        "EZMicroBalanceCode/Ascension/Combat/AscensionCombatTracker.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionDiagnostics.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionExpansionConfig.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionFeatureGate.Environment.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionFeatureGate.Systems.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionFeatureGate.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionInitializer.cs",
        "EZMicroBalanceCode/Ascension/Core/MultiplayerFeaturePolicy.cs",
        "EZMicroBalanceCode/Ascension/Core/MultiplayerDiagnostics.JoinFlow.cs",
        "EZMicroBalanceCode/Ascension/Core/MultiplayerDiagnostics.Lobby.cs",
        "EZMicroBalanceCode/Ascension/Core/MultiplayerDiagnostics.RunState.cs",
        "EZMicroBalanceCode/Ascension/Core/MultiplayerDiagnostics.SaveQuit.cs",
        "EZMicroBalanceCode/Ascension/Map/A11MapGeometryProof.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapQuestMarker.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.A11Geometry.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.A11GeometryDiagnostics.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.A11InsertedColumnChoice.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.A11SerializableGraph.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.A11SerializableMutations.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.A11WidthAndRows.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.DeepBranches.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.DeepBranches.Existing.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.DeepBranches.Layout.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.DeepBranches.Planning.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.DeepBranches.RouteSafety.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.MapGraphHelpers.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.MarkerHelpers.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.MarkerOrdering.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.Markers.Banners.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.Markers.BossSeals.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.Markers.Diagnostics.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.Markers.Firemarks.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.MarkerSelection.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionMapService.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionMapBannerHoverPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionMapBossSealHoverPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionMapDeepBranchHoverPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionMapFiremarkHoverPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionMapIconPatches.cs",
        "EZMicroBalanceCode/Ascension/Map/AscensionNodeMetadata.cs",
        "EZMicroBalanceCode/Ascension/Rewards/AscensionRewardService.cs",
        "EZMicroBalanceCode/Ascension/Rewards/AscensionRewardService.CardOptions.cs",
        "EZMicroBalanceCode/Ascension/Rewards/AscensionRewardService.Fission.cs",
        "EZMicroBalanceCode/Ascension/Rewards/AscensionRewardService.RoomRewards.cs",
        "EZMicroBalanceCode/Ascension/Core/AscensionSavedStateFields.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionSelectionPatches.cs",
        "EZMicroBalanceCode/Ascension/Patches/AscensionSelectionRunStartPatches.cs",
        "EZMicroBalanceCode/Ascension/Map/BannerRoomMapQuestMarker.cs",
        "EZMicroBalanceCode/Ascension/Rewards/BossSealCatalog.Definitions.cs",
        "EZMicroBalanceCode/Ascension/Rewards/BossSealCatalog.Localization.cs",
        "EZMicroBalanceCode/Ascension/Rewards/BossSealDefinition.cs",
        "EZMicroBalanceCode/Ascension/Cards/BossSealCards.cs",
        "EZMicroBalanceCode/Ascension/Cards/RootCards.cs",
        "EZMicroBalanceCode/Ascension/Events/A20Courtyard.cs",
        "EZMicroBalanceCode/Ascension/Map/FiremarkedEliteMapQuestMarker.cs",
        "EZMicroBalanceCode/Ascension/Enchantments/FissionEnchantment.cs",
        "EZMicroBalanceCode/Ascension/Rewards/ForgeTokenService.cs",
        "EZMicroBalanceCode/Ascension/Rewards/ForgeTokenService.VisibleRelic.cs",
        "EZMicroBalanceCode/Ascension/Core/MultiplayerDiagnostics.cs",
        "EZMicroBalanceCode/Ascension/Powers/AscensionPowerAmountHelper.cs",
        "EZMicroBalanceCode/Ascension/Powers/AeonglassHourglassPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/BannerBloodPrizePowers.cs",
        "EZMicroBalanceCode/Ascension/Powers/BannerLastStandPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/BannerPowers.cs",
        "EZMicroBalanceCode/Ascension/Powers/BannerPressingLinePower.cs",
        "EZMicroBalanceCode/Ascension/Powers/BannerShieldwallPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/BannerVanguardPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/BoilingCriticalPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/BossSealPowers.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkConstantHealPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkForgeArmorPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkGiantPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkHeatPowers.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkMightPower.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkMoltenCorePower.cs",
        "EZMicroBalanceCode/Ascension/Powers/FiremarkPowers.cs",
        "EZMicroBalanceCode/Ascension/Powers/HolyDazePower.cs",
        "EZMicroBalanceCode/Ascension/Powers/ResidualSamplePower.cs",
        "EZMicroBalanceCode/Ascension/Relics/ForgeTokenRelic.cs",
        "EZMicroBalanceCode/Ascension/Enchantments/RoyalDecreeEnchantment.cs",
        "EZMicroBalanceCode/Ascension/Combat/RootBudCombatHook.cs",
        "EZMicroBalanceCode/Ascension/Combat/RootBudCombatHook.CardFlow.cs",
        "EZMicroBalanceCode/Ascension/Combat/RootBudCombatHook.CombatEvents.cs",
        "EZMicroBalanceCode/Ascension/Combat/RootBudCombatHook.Helpers.cs",
        "EZMicroBalanceCode/Ascension/Combat/RootBudCombatHook.Lifecycle.cs",
        "EZMicroBalanceCode/Ascension/Cards/RootBudCard.cs",
        "EZMicroBalanceCode/Ascension/Cards/RootFamilyCard.cs",
        "EZMicroBalanceCode/Ascension/Cards/RootPortraitPaths.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.DeckCards.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.Lifecycle.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.Notices.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.PendingDowngrades.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.Removals.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.State.cs",
        "EZMicroBalanceCode/Ascension/Rewards/RootDeckService.cs",
        "EZMicroBalanceCode/Ascension/Patches/RootRunHook.cs",
        "EZMicroBalanceCode/Config/EZMicroBalanceModConfig.cs",
        "EZMicroBalanceCode/Diagnostics/ReleaseEvidenceLog.cs",
        "EZMicroBalanceCode/Diagnostics/SpirePlusAncientLiveTestConsoleCmd.cs",
        "EZMicroBalanceCode/Map/SpirePlusMapPointHoverComposer.cs",
        "EZMicroBalanceCode/Preview/CrystalSpherePeekPatch.cs",
        "EZMicroBalanceCode/Preview/PreviewLog.cs",
        "EZMicroBalanceCode/Preview/TransformPredictionRngContext.cs",
        "EZMicroBalanceCode/Preview/TransformPredictionService.cs",
        "EZMicroBalanceCode/Preview/TransformPreviewPatch.cs",
        "EZMicroBalanceCode/MainFile.cs"
    ];

    [Fact]
    public void ActiveSourceFilesAreCoveredByTheGuardManifest()
    {
        var activeSources = Directory.GetFiles(RepoPath("EZMicroBalanceCode"), "*.cs", SearchOption.AllDirectories)
            .Select(path => ToRepoRelativePath(path))
            .Where(path => path != "EZMicroBalanceCode/Ancients/GlobalUsings.cs")
            .OrderBy(path => path, StringComparer.Ordinal)
            .ToArray();

        Assert.Equal(ExpectedActiveSourceFiles.OrderBy(path => path, StringComparer.Ordinal), activeSources);

        var coverageRoots = IndependentCoverageRoots;
        var uncoveredSources = activeSources
            .Where(activeSource => !coverageRoots.Any(root => root.Covers(activeSource)))
            .ToArray();

        Assert.Empty(uncoveredSources);

        foreach (var root in coverageRoots)
        {
            Assert.Contains(activeSources, activeSource => root.Covers(activeSource));
            Assert.NotEqual($"{nameof(ActiveSourceManifestGuardTests)}.cs", root.GuardTestFile);

            var guardSource = ReadRepoText("tests", "EZMicroBalance.Tests", root.GuardTestFile);
            Assert.Contains(root.GuardEvidenceSnippet, guardSource, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void OnlySpirePlusIsAnActiveRootModSurface()
    {
        foreach (var removedRootSurface in new[]
        {
            "EzDailyContent",
            "EzDailyContentCode",
            "EzDailyContent.json",
            "EZFuturePeek",
            "EZFuturePeekCode",
            "EZFuturePeek.csproj",
            "EZFuturePeek.json",
            "EZFuturePeek.sln",
            Path.Combine("tests", "EZFuturePeek.Tests")
        })
        {
            Assert.False(Directory.Exists(RepoPath(removedRootSurface)), $"{removedRootSurface} should not remain as an active mod directory.");
            Assert.False(File.Exists(RepoPath(removedRootSurface)), $"{removedRootSurface} should not remain as an active mod file.");
        }
    }

    private static readonly SourceCoverageRoot[] IndependentCoverageRoots =
    [
        new("EZMicroBalanceCode/Ancients/Common/", "ReleaseCoverageGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ancients\")"),
        new("EZMicroBalanceCode/Ancients/Patches/", "AncientBehaviorGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ancients\", \"Patches\")"),
        new("EZMicroBalanceCode/Ancients/Expansion/Urda/", "UrdaReleaseCoverageGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ancients\", \"Expansion\", \"Urda\")"),
        new("EZMicroBalanceCode/Ancients/Expansion/Morvi/", "MorviV22GuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ancients\", \"Expansion\", \"Morvi\")"),
        new("EZMicroBalanceCode/Ancients/Expansion/Lotha/", "LothaPolishGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ancients\", \"Expansion\", \"Lotha\")"),
        new("EZMicroBalanceCode/Ancients/Expansion/Vakuu/", "VakuuTemptationGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ancients\", \"Expansion\", \"Vakuu\")"),
        new("EZMicroBalanceCode/Ascension/", "AscensionFeatureGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\", \"Ascension\")"),
        new("EZMicroBalanceCode/Config/", "ReleaseSafetyExpandedGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\")"),
        new("EZMicroBalanceCode/Diagnostics/", "ReleaseSafetyExpandedGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\")"),
        new("EZMicroBalanceCode/Map/", "AncientHighRiskSourceGuardTests.cs", "ReadRepoText(\"EZMicroBalanceCode\", \"Map\", \"SpirePlusMapPointHoverComposer.cs\")"),
        new("EZMicroBalanceCode/Preview/", "PreviewToolsGuardTests.cs", "CrystalSpherePatchOnlyTouchesTheMaskAndButton"),
        new("EZMicroBalanceCode/MainFile.cs", "ReleaseSafetyExpandedGuardTests.cs", "ReadSourceTree(\"EZMicroBalanceCode\")")
    ];

    private sealed record SourceCoverageRoot(string PathPrefix, string GuardTestFile, string GuardEvidenceSnippet)
    {
        public bool Covers(string activeSource)
        {
            return PathPrefix.EndsWith(".cs", StringComparison.Ordinal)
                ? activeSource.Equals(PathPrefix, StringComparison.Ordinal)
                : activeSource.StartsWith(PathPrefix, StringComparison.Ordinal);
        }
    }
}
